// data.js
const mediaData = [
  // --- FILMS ---
  {
    id: 101,
    type: 'movie',
    title: "Transformers",
    year: 2007,
    genres: ["Action", "Sci-Fi"],
    duration: "2h 24m",
    imdb: 7.0,
    rottenTomatoes: 58,
    synopsis: "An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.",
    posterUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCcMHSQ6XnNGz04CMj2vBnoRq60AyjCQbexKkDe7NiWb3DYsS8WgZomIochqKlU0m3pX7lScoLnoZlxLtPbtI9PTl_fCAczLmzTcKYyXN0t9VaOOeebzWwTSDm38MIxHIEBnofFO5eQ0YF_ZJqXhHRjoy55k0Wq4VERsTFfDFKHlOQtYJub6GQxsVA1dAwe28lq_4S9etlRQE6P7XRG0GsOpI4BTelWrP9g_z-unEw4Q6UUK0CKozlCLVrZb9f1ijxsEYQkuYLRNe_X",
    bannerUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBLdL9my04EmTsH3s6DVZnMnidYvRmUzLmdtqtpuRIefnobhclLR-Niei2u9w13d8qtJLIYhdNMmq_wa8NJsINDGnBDwu34z-gPClqK_O9-TxiWjAzASjBFgoxfr0DJLgb3dOo7wYn-IQQ8NjnMvQ4ou9gXzjsk23n6NXbOaM44vn--9saTjge5iJJnPMScbr3sKTXHUg4WiaUjyyciaG77FifLq_M_U7Io3J7W81z6TZCATBjVuHsRFTV7rUNKgNBou9kk1LqoR-xW",
    director: { name: "Michael Bay", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtnwXz5DuJb9BSDxk3GFAHXRYwXD1e55QumwFc_1Vx5RuO1U6WUiF5RleeTZFbloeDF7Xtv6kIACcUN6eB2yHc6qSGvDIPlHkvfs89jvO8Rwf2SQ2_IPIZIBbEnquG-qNtLBMQBgrEYlMUer0EJpeSXrbNOTfd0fAu3dwBV-LP3wSbzW4ffy6SpXKW97X957N7a7sIExyY-dSqCQgoLWwHxFWCbxhHVjCIWlKMZC8sZ0NpOLhth_2Xlmey6dtxITPrEEgXSAQq-6yD" },
  },
  {
    id: 102,
    type: 'movie',
    title: "The Midnight Bloom",
    year: 2023,
    genres: ["Drama", "Mystery"],
    duration: "1h 58m",
    imdb: 8.2,
    rottenTomatoes: 85,
    synopsis: "A reclusive botanist discovers a flower that blooms only at midnight, revealing secrets from her family's past.",
    posterUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAMXwL__aHQ2pz5zRYJMHOooiXjigxnyq-FzFDfNm3hKo6-Ncc_vBPZN5XJDgtMSvEKaLM1XogXi_yoVD6IOZGMG0b-MYyrorxPfm6nzkLrjDGC9iXw2bTzO9bvo822mZ3w9c522bp0lhF_RcPi45nBi7BaJZYrE3uZh71LpVRFap7WwBNW6DTV-r08ybZiR8bRUN2E912Joo9QLZ80LabL9QY8iLAq82MduoX9tuUJH7IYPkBVoTM1z-0fBSIZFRB4OskIZxijMcUr",
    bannerUrl: "https://placehold.co/600x320/1a1a1a/ffffff?text=Midnight+Bloom",
    director: { name: "Jane Doe", imageUrl: "https://placehold.co/64x64" },
  },
  {
    id: 103,
    type: 'movie',
    title: "Crimson Horizon",
    year: 2022,
    genres: ["Adventure", "Action"],
    duration: "2h 10m",
    imdb: 8.5,
    rottenTomatoes: 92,
    synopsis: "A team of explorers searches for a lost city on Mars, only to find they are not alone.",
    posterUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDGh7s-D5NbmWhAkhPvmznLgKHE-opqG4wcC9h-xuRwj7tFVb_-nl4RRrVocjzRHesU21Cpq8xLYSidAiEMNzgaMe-gP7lqheWDL7kjM24CD-6noWr2l8D3MEKAnvqE5_HqYTa1M2K3xxPsVAN-8QrQv-c21hZbg_TBTazgBIN7OJsw8-AS17lLMVIgiUV6Jgo4-cEFQJ9f8vv_EoJ6DcsyIGx72HYqSPrs9Ad1Vlxmp9NBUPNHnNqMwNbOXE8JojKNVy_A_p2r7DMe",
    bannerUrl: "https://placehold.co/600x320/ea2a33/ffffff?text=Crimson+Horizon",
    director: { name: "John Smith", imageUrl: "https://placehold.co/64x64" },
  },
  {
    id: 104,
    type: 'movie',
    title: "Starlight Serenade",
    year: 2021,
    genres: ["Romance", "Musical"],
    duration: "2h 05m",
    imdb: 7.5,
    rottenTomatoes: 80,
    synopsis: "Two aspiring musicians in a bustling city fall in love while chasing their dreams.",
    posterUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuD7NMkoa-b0AuvCCtXfJx_VFvwW7P3k2_e_LNJ3NAuJV-oqLMhY93jI--h3jJnNStM1HwRMNeyEriogrvbY4gPwHip-0LhtAtMWcC4el_-gMK4IjYY2AN_G2C2VWg-_033K_9zgl3XDOK6U2kW-78q4tPiovnZLc1-SuUZkri_KWLGiitGz4fgISfyX_naPNNLvfBELwXKrIIVPwcNm4AGkggPH9l_Nzpv8PG7cuGklUVOPNUMppQGu1TTVWIUDGNTCvXixa8SQ3Pek",
    bannerUrl: "https://placehold.co/600x320/5b21b6/ffffff?text=Starlight+Serenade",
    director: { name: "Emily White", imageUrl: "https://placehold.co/64x64" },
  },
  {
    id: 105,
    type: 'movie',
    title: "The Silent Symphony",
    year: 2020,
    genres: ["Thriller", "Drama"],
    duration: "1h 45m",
    imdb: 8.8,
    rottenTomatoes: 95,
    synopsis: "A deaf composer creates a masterpiece that holds the key to a city-wide conspiracy.",
    posterUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1c-tvgNNquDAzDlu3K9YOBBj6TaadceZrXB-DjY7mrEOvkPS6EopWlArs__e0SKUsSmkloQPNURSvXGb4iu_rPGqJB1PvlxPkMh-H2AhW-nV3uiB-t1S9KB4nqhY4TOhvUek5qMbZfiGkvWCNByxuq5WJHB7qFalFW4PNAVQNIch_18gAo455LEl9dAi2-4ospJZWkgeGntQ1Y661wfNjdcVZAml1diQqlhiVCT_YoE6nwebOhdSM3qaZi6GdrLbWB9SDLIeSv8nc",
    bannerUrl: "https://placehold.co/600x320/4b5563/ffffff?text=Silent+Symphony",
    director: { name: "Chris Black", imageUrl: "https://placehold.co/64x64" },
  },

  // --- SERIES ---
  {
    id: 201,
    type: 'serie',
    title: "Future Echoes",
    year: 2023,
    genres: ["Sci-Fi", "Drama"],
    seasons: 3,
    imdb: 8.5,
    rottenTomatoes: 91,
    synopsis: "In a future where memories can be extracted and re-lived, a detective uses the technology to solve crimes, but uncovers a conspiracy that threatens the very fabric of reality.",
    posterUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFZ9YuOG6HkODPvcIvh69GSxADK7DTbEumyFYWsuCk0nfI99kpTs7rdIlvCuP0Io3VNZNX9yJynUQ57wocNcg5xLsFKIwAitJp6Aap7zIWVYYWkIeSlfI5-f4mOMETx2HlxzoKXHlz2SW00KfAG9GU3X35_24VWfTXVJp-pT3cSBd58ZXOAXIxWt8ZUxyb92fnxZJevCqWOzdB91jmKQ4gqg8nXdu0tdZMJ-Kljp_m8WIae1LRx630koilJjgG7cH1el8Xr5eDC1aM",
    bannerUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuD4ejFWbSCijxwtUPjPxBsrhg5z7OwxrTmcmTiciNn-a0i8qMx8RadaaBtD6_E-V94lnZlbwLo9svap_TlTxoGak2L42AnJ5RKlXX5I4RHERpxthiZ16zEgjY4SRdi6LiM0dBuYUbtBii51n2EFtfIWS2XULbd4NdEHmVTyYZNBLu3Wvm-zoKL0781GJgc6ovtThCyMlI-5Ec0WKabk1KkeNn0Hgcuctn09fwYeqZfW3VmqgbexvxoM2lttrmQYFoIG-ITBDs9GZcjI",
    creator: { name: "Elara Vance", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB7LRtTFL60Rpw3tAALhto1cn3FJ71NRS3NcE2gfAh2svNth-A5s0ujY3tPyYktCHjOiA2QxPaxDlwcxzfwTTK2LyzAggn39AxO7vaQnUtli-6CqLA_XVqGw0_9dYeSwX9IoX1hgHayyo8SKSctU1KzZc7OIBo802czLe20RG1vXLE4XhU5kBOk6vyHPD7m7Khy7EZh1Hj8MpVFn8GmSsLOnFJIAIuFp0Hc_cPaktu3MyigC_PHsb8arwFpQKWJ3POWo9ivfkhk6387" },
  },
  {
    id: 202,
    type: 'serie',
    title: "The Gilded Cage",
    year: 2022,
    genres: ["Period Drama", "Politics"],
    seasons: 2,
    imdb: 8.7,
    rottenTomatoes: 94,
    synopsis: "A look at the lives of the wealthy elite in 1880s New York, exploring the clash between old money and new.",
    posterUrl: "https://placehold.co/192x288/eab308/000000?text=Gilded+Cage",
    bannerUrl: "https://placehold.co/600x320/eab308/000000?text=Gilded+Cage",
    creator: { name: "Arthur Finch", imageUrl: "https://placehold.co/64x64" },
  },
  {
    id: 203,
    type: 'serie',
    title: "Northwood",
    year: 2024,
    genres: ["Crime", "Thriller"],
    seasons: 1,
    imdb: 8.1,
    rottenTomatoes: 89,
    synopsis: "In a remote northern town, a series of strange disappearances forces a retired sheriff back into action.",
    posterUrl: "https://placehold.co/192x288/6b7280/ffffff?text=Northwood",
    bannerUrl: "https://placehold.co/600x320/6b7280/ffffff?text=Northwood",
    creator: { name: "Sarah Jenkins", imageUrl: "https://placehold.co/64x64" },
  },
  {
    id: 204,
    type: 'serie',
    title: "The Alchemist's Heir",
    year: 2021,
    genres: ["Fantasy", "Adventure"],
    seasons: 4,
    imdb: 8.3,
    rottenTomatoes: 90,
    synopsis: "A young woman inherits a mysterious alchemy shop and discovers she is part of a hidden world of magic.",
    posterUrl: "https://placehold.co/192x288/166534/ffffff?text=Alchemist",
    bannerUrl: "https://placehold.co/600x320/166534/ffffff?text=Alchemist's+Heir",
    creator: { name: "Leo Maxwell", imageUrl: "https://placehold.co/64x64" },
  },
  {
    id: 205,
    type: 'serie',
    title: "Zero Gravity",
    year: 2025,
    genres: ["Sci-Fi", "Comedy"],
    seasons: 2,
    imdb: 7.8,
    rottenTomatoes: 85,
    synopsis: "The chaotic daily lives of the dysfunctional crew aboard a commercial spaceship on a long-haul cargo run.",
    posterUrl: "https://placehold.co/192x288/6d28d9/ffffff?text=Zero+G",
    bannerUrl: "https://placehold.co/600x320/6d28d9/ffffff?text=Zero+Gravity",
    creator: { name: "Mika Chen", imageUrl: "https://placehold.co/64x64" },
  }
];